format = """
${custom.fish}\
$username\
$hostname\
$directory\
${custom.git_remote}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$python\
$ruby\
$rust\
$aws\
$gcloud\
$kubernetes\
$terraform \
$helm\
$cmd_duration\
$jobs\
$line_break\
$battery\
$time\
$shlvl\
$character\
"""

# format = "$all"

# Core
[character]
success_symbol = "[➜](bright-green)"
error_symbol = "[»](bright-red)"

[username]
show_always = false
style_user = "bright-yellow"

[hostname]
ssh_only = true
style = "bright-purple"

[cmd_duration]
min_time = 5000

[directory]
# style = "#00E676"
style = "bright-green"
read_only = " "
# truncate_to_repo = false

[shlvl]
disabled = false
symbol = " "
threshold = 2
style = "bright-yellow"
format = "([$symbol\\[$shlvl\\]]($style) )"

# Cloud
# ------------------------
[aws]
symbol = " "
format = "[$symbol ($profile)]($style) "

[gcloud]
disabled = true
symbol = " "

# Battery
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

# Git Stuff
# ------------------------
[git_branch]
symbol = " "
style = "#FF9100"
format = "on [$symbol$branch]($style) "
truncation_length = 8

[git_commit]
# Tag
tag_disabled = true
tag_symbol = "狀 "

# Commit Hash
only_detached = false
style = "bright-yellow"
format = "[ $hash ]($style)"
commit_hash_length = 7

[git_status]
style = "#F05032"
deleted = "-"
untracked = "?"
renamed = "»"
ahead = "↑"
behind = "↓"
diverged = "↕"

[custom.git_remote]
disabled = false
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    echo " "
elif [[ "$GIT_REMOTE" =~ "codecommit" ]]; then
    echo " "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    echo " "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    echo " "
else
    echo " "
fi
"""
style = "#FF9100"
directories = [".git"]
shell = ["bash", "--noprofile", "--norc"]
format = "(at $output) "


[custom.fish]
description = "This is a fish shell"
symbol = " "
style = "#DEA584"
when = '[ "$STARSHIP_SHELL" == "fish" ]'
shell = ["bash", "--noprofile", "--norc"]

# enable/disable
disabled = false


# Kubernetes
# --------------------
[kubernetes]
disabled = false
symbol = "ﴱ "
style = "#4980f4"

[helm]
symbol = "⚙"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "#00ADD8"

[python]
python_binary = "python3"
symbol = " "
style = "#FFD43B"

[package]
# symbol = " "
symbol = " "
disabled = false

[time]
disabled = false
format = "[\\[$time\\]]($style) "
use_12hr = true
style = "bold #4FC3F7"
# style = "bright-green"

[terraform]
disabled = true
symbol = " "
format = "[$symbol\\[$workspace\\]]($style)"
style = "#735686"

# Disable not needed
# --------------------
[docker_context]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[cmake]
disabled = true

[dotnet]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[env_var]
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
disabled = true

[lua]
symbol = " "
disabled = true

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
disabled = true

[openstack]
symbol = "  "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[purescript]
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
style = "#DEA584"
disabled = true

[singularity]
disabled = true

[swift]
symbol = "ﯣ "
disabled = true

[status]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true
