format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$python\
$ruby\
$rust\
$aws\
$gcloud\
$kubernetes\
$helm\
$cmd_duration\
$jobs\
$line_break\
$battery\
$time\
$character\
$custom
"""

# format = "$all"

# Core
[character]
success_symbol = "[»](#FAFAFA)"
error_symbol = "[»](red)"

[username]
disabled = false
show_always = false
style_user = "#d386ff"

[hostname]
ssh_only = true
symbol = " "
style = "#E95420"

[cmd_duration]
min_time = 5000

[directory]
style = "#00E676"

# Cloud
# ------------------------
[aws]
#disabled = true
symbol = " "
format = "[$symbol]($style) "

[gcloud]
#disabled = true
format = "[$symbol]($style) "
symbol = " "

# Battery
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

# Git Stuff
# ------------------------
[git_branch]
symbol = " "
style = "#FF9100"
truncation_length = 8

[git_commit]
style = "#CE93D8"
format = "[ $hash ]($style)"
commit_hash_length = 7
only_detached = false

[git_status]
style = "#F05032"
deleted = "⎼"
untracked = "?"
renamed = "»"
ahead = "↑"
behind = "↓"
diverged = "↕"

# Kubernetes
# --------------------
[kubernetes]
disabled = false
symbol = "ﴱ "
style = "#4980f4"

[helm]
symbol = "⚙"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "#00ADD8"

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}${version} \\($virtualenv\\)]($style) "
style = "#FFD43B"

[ruby]
symbol = " "

[rust]
symbol = " "
style = "#DEA584"

[time]
disabled = false
format = "[\\[$time\\]]($style) "
use_12hr = true
style = "#4FC3F7"

# Usually disabled
[terraform]
disabled = true
symbol = "⚒ "
style = "#623CE4"

# Disable not needed
# --------------------
[docker_context]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[dotnet]
disabled = true

[dart]
symbol = " "
disabled = true

[env_var]
disabled = true

[elixir]
disabled = true
symbol = " "

[elm]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
symbol = "ﯣ "
disabled = true

[zig]
disabled = true
