format = """
$username\
$hostname\
$directory\
${custom.git_remote}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$conda\
$python\
$ruby\
$rust\
$aws\
$gcloud\
$kubernetes\
$terraform \
$helm\
$cmd_duration\
$line_break\
$shell\
$battery\
$time\
$jobs\
$shlvl\
$character\
"""

# format = "$all"

# Core
# ﬏  ﬦ      﫟   
# Extra OS Logos
# Ubuntu     - 
# Lubuntu    - 
# Fedora     - 
# OpenBSD    - 
# Raspbian   - 
# Arch Linux - 
# Manjaro    - 
# Linux Mint - 
# Rocky      - 
# Windows    - 
# Qubes      - 
# Open Suse  - 
# Linux      - 

[character]
success_symbol = "[»](bright-green)"
error_symbol = "[»](bright-red)"


[username]
show_always = false
style_user = "bright-yellow"

[hostname]
ssh_only = true
style = "bright-purple"

[cmd_duration]
min_time = 5000

[directory]
style = "#99d066"
# style = "bright-green"
read_only = " "
# truncate_to_repo = false

[shlvl]
disabled = false
symbol = " "
threshold = 2
style = "bright-yellow"
format = "([$symbol\\[$shlvl\\]]($style) )"

[jobs]
symbol = "羽"
format = "[$symbol\\[($number)\\]]($style)"
style = "blue"
threshold = 0

# Cloud
# ------------------------
[aws]
# symbol = " "
symbol = " "
format = "[$symbol $profile(\\($region\\))]($style) "
[aws.region_aliases]
eu-west-1 = "IR"
eu-central-1 = "DE"
us-east-1 = "US-E"
us-west-1 = "US-W"


[gcloud]
# symbol = " "
disabled = true
symbol = " "
style = "blue"
format = "[$symbol$account(\\($region\\))]($style) "

# Uncomment after az module is available
# [azure]
# symbol = " "

# Battery
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

# Git Stuff
# ------------------------
[git_branch]
symbol = " "
style = "#FF9100"
format = "[$symbol$branch]($style) "
truncation_length = 16

[git_commit]
# Tag
tag_disabled = false
tag_symbol = "狀 "

# Commit Hash
only_detached = true
style = "#ffb04c"
#format = "[ $hash ]($style)"
format = "[ $hash ($tag) ]($style)"
commit_hash_length = 7

[git_status]
style = "#F05032"
deleted = "-"
untracked = "?"
renamed = "»"
ahead = "↑"
behind = "↓"
diverged = "↕"
# ahead = "↑${count}"
# diverged = "↕ ↑${ahead_count} ↓${behind_count}"
# behind = "↓${count}"

# Format
# ahead_count behind_count
# ([\[$all_status$ahead_behind\]]($style) )
# format = "$conflicted$stashed$deleted$renamed$modified$staged$untracked"

[custom.git_remote]
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
GIT_HOST=$(printf "%s" "$GIT_REMOTE" | sed -e 's/[^/]*\\/\\/\\([^@]*@\\)\\?\\([^:/]*\\).*/\\2/')
if [[ "$GIT_HOST" =~ ^github.com ]]; then
    printf  " "
elif [[ "$GIT_HOST" =~ ^github* ]]; then
    printf  " ${GIT_HOST}"
elif [[ "$GIT_HOST" =~ git-codecommit.([^/]*).amazonaws.com ]]; then
    printf  "  ${BASH_REMATCH[1]}"
elif [[ "$GIT_HOST" =~ "gitlab.com" ]]; then
    printf  " "
elif [[ "$GIT_HOST" =~ ^gitlab.com|^gitlab* ]]; then
    printf  "  ${GIT_HOST}"
elif [[ "$GIT_HOST" =~ "bitbucket.com" ]]; then
    printf  " "
elif [[ "$GIT_HOST" =~ ^gitea* ]]; then
    printf  " ${GIT_HOST}"
elif [[ "$GIT_HOST" =~ "git.launchpad.net" ]]; then
    printf  " "
elif [[ "$GIT_HOST" =~ ^(ssh.dev.azure.com|dev.azure.com|vs-ssh.visualstudio.com|visualstudio.com) ]]; then
    printf  " "
elif [[ "$GIT_HOST" =~ ^developers.google.com* ]]; then
    printf  " "
elif [[ "$GIT_HOST" == "aur.archlinux.org" ]]; then
    printf  " "
elif [[ "$GIT_HOST" == "salsa.debian.org" ]]; then
    printf  " "
elif [[ "$GIT_HOST" == "src.fedoraproject.org" ]]; then
    printf  " "
elif [[ "$GIT_HOST" == "" ]]; then
    printf  " "
else
    printf " ${GIT_HOST}"
fi
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
style = "#FF6090"
shell = ["bash", "--noprofile", "--norc"]
format = "(at [$output ]($style))"

# Kubernetes
# --------------------
[kubernetes]
disabled = false
# symbol = "ﴱ "
symbol = " "
format = '(on [$symbol$context( \($namespace\))]($style)) '
style = "#5e92f3"

[helm]
# symbol = "⚙"
symbol = " "

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "#00ADD8"

[python]
python_binary = "python3"
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '
style = "#FFD43B"

[conda]
symbol = " "
style = "#44A833"
format = "[$symbol$environment]($style) "

[package]
#symbol = " "
symbol = " "
style = "#ff833a"
disabled = false

[shell]
fish_indicator = ""
bash_indicator = ""
powershell_indicator = "_"
disabled = false


[time]
disabled = false
format = "[\\[$time\\]]($style) "
use_12hr = true
style = "#4FC3F7"
time_format = "%I:%M %p"

[terraform]
disabled = false
symbol = " "
format = "[$symbol\\($workspace\\)]($style) "
style = "#9a67ea"

# Disable not needed
# --------------------
[docker_context]
symbol = " "
disabled = true

[cmake]
disabled = true

[dotnet]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[env_var]
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
disabled = true

[lua]
symbol = " "
disabled = true

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
disabled = true

[openstack]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[purescript]
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
style = "#DEA584"
disabled = true

[singularity]
symbol = " "
style = "#ED1944"
disabled = false

[swift]
symbol = "ﯣ "
disabled = true

[status]
disabled = false

[vagrant]
disabled = true

[zig]
disabled = true
