# format = """\
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $package\
# $golang\
# $python\
# $rust\
# $gcloud\
# $aws\
# $kubernetes\
# $helm\
# $terraform\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $character\
# """

format = "$all"

# Core

[character]
success_symbol = "[➜](green) "
error_symbol = "[✖](red) "

[username]
disabled = false
show_always = false
style_user = "#d386ff"

[hostname]
ssh_only = true
symbol = " "
style = "#E95420"

[cmd_duration]
min_time = 5000

[directory]
style = "#A6CE39"

# Cloud
# ------------------------
[aws]
symbol = "  "
style = "#FF9900"

[gcloud]
disabled = true
symbol = " "


# Git Stuff
# ------------------------
[git_branch]
symbol = " "
style = "#FF8800"
truncation_length = 8

[git_commit]
style = "#FFBB00"
format = "[ $hash ]($style)"
commit_hash_length = 7
only_detached = false

[git_status]
style = "bold #F05032"
deleted = "-"

# Kubernetes
# --------------------
[kubernetes]
symbol = "ﴱ "
style = "#4980f4"

[golang]
symbol = " "
style = "#00ADD8"

[python]
symbol = " "
style = "#FFD43B"

[rust]
symbol = " "
style = "#DEA584"

[terraform]
symbol = " "
style = "#623CE4"

# Disable not needed features
# --------------------
[docker_context]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[ruby]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[zig]
disabled = true
